wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/contracts/
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Adygeja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altaj_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altajskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Amurskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Arkhangelskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Astrakhanskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bajkonur_g/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bashkortostan_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Belgorodskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Brjanskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Burjatija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chechenskaja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Cheljabinskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chukotskij_AO/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chuvashskaja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Dagestan_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Evrejskaja_Aobl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ingushetija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Irkutskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ivanovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jamalo-Neneckij_AO/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jaroslavskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kabardino-Balkarskaja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaliningradskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kalmykija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaluzhskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kamchatskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karachaevo-Cherkesskaja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karelija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kemerovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khabarovskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khakasija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khanty-Mansijskij_AO-Jugra_AO/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kirovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Komi_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kostromskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnodarskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnojarskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krim_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurganskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Leningradskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Lipeckaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Magadanskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Mordovija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskva/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Murmanskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Neneckij_AO/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Nizhegorodskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novgorodskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novosibirskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Omskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orenburgskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orlovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/PG-PZ/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Penzenskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Permskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Primorskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Pskovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rjazanskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rostovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakha_Jakutija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakhalinskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Samarskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sankt-Peterburg/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Saratovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sevastopol_g/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Severnaja_Osetija-Alanija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Smolenskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Stavropolskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sverdlovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tambovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tatarstan_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tjumenskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tomskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tulskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tverskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tyva_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Udmurtskaja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Uljanovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vladimirskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Volgogradskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vologodskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Voronezhskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Zabajkalskij_kraj/contracts
