wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sankt-Peterburg/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Saratovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sevastopol_g/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Severnaja_Osetija-Alanija_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Smolenskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Stavropolskij_kraj/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sverdlovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tambovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tatarstan_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tjumenskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tomskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tulskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tverskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tyva_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Udmurtskaja_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Uljanovskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vladimirskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Volgogradskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vologodskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Voronezhskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Zabajkalskij_kraj/contracts
