wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Adygeja_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altaj_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altajskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Amurskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Arkhangelskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Astrakhanskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bajkonur_g/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bashkortostan_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Belgorodskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Brjanskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Burjatija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chechenskaja_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Cheljabinskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chukotskij_AO/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chuvashskaja_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Dagestan_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Evrejskaja_Aobl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ingushetija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Irkutskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ivanovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jamalo-Neneckij_AO/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jaroslavskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kabardino-Balkarskaja_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaliningradskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kalmykija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaluzhskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kamchatskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karachaevo-Cherkesskaja_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karelija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kemerovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khabarovskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khakasija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khanty-Mansijskij_AO-Jugra_AO/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kirovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Komi_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kostromskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnodarskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnojarskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krim_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurganskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Leningradskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Lipeckaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Magadanskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Mordovija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskva/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Murmanskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Neneckij_AO/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Nizhegorodskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novgorodskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novosibirskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Omskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orenburgskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orlovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/PG-PZ/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Penzenskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Permskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Primorskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Pskovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rjazanskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rostovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakha_Jakutija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakhalinskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Samarskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sankt-Peterburg/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Saratovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sevastopol_g/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Severnaja_Osetija-Alanija_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Smolenskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Stavropolskij_kraj/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sverdlovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tambovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tatarstan_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tjumenskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tomskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tulskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tverskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tyva_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Udmurtskaja_Resp/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Uljanovskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vladimirskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Volgogradskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vologodskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Voronezhskaja_obl/protocols
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Zabajkalskij_kraj/protocols
